 platform :ios, '9.0'

target 'DrakHorseWork' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DrakHorseWork

pod 'AMap3DMap', '~> 4.1.0'
pod 'AMapSearch', '~> 4.5.0'  #搜索功能

end
